---

- name: Clone Pole Emploi repository
  git:
    repo: 'https://github.com/BinomeEPSI/epsi-i4-workshop-pe.git'
    dest: /opt/pole-emploi

- name: Install dependencies
  npm:
    path: /opt/pole-emploi

- name: Set permissions on Pole Emploi Repository
  file:
    path: /opt/pole-emploi
    state: directory
    owner: "{{ nodejs_user }}" 
    group: "{{ nodejs_user }}" 
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Create configuration file for server
  template:
    src: app-config.js.j2
    dest: /opt/pole-emploi/app/config.js
    owner: "{{ nodejs_user }}"
    group: "{{ nodejs_user }}"
    mode: 0644

- name: Create configuration file for front-end
  template:
    src: pe-js-config.js.j2
    dest: /opt/pole-emploi/pe-js/config.js
    owner: "{{ nodejs_user }}"
    group: "{{ nodejs_user }}"
    mode: 0644

- name: Create service file 
  template:
    src: poleemploi.service.j2
    dest: /etc/systemd/system/poleemploi.service
    owner: root
    group: root
    mode: 0644

- name: Start Pole Emploi Node Server and set it boot by default
  systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: poleemploi.service

- include: nginx_configuration.yml