---

- name: Clone Pole Emploi repository
  git:
    repo: 'https://github.com/EPSIBordeaux/epsi-i4-workshop-pe.git'
    dest: "{{ pole_emploi.path }}"

- name: Install dependencies
  npm:
    path: "{{ pole_emploi.path }}"

- name: Set permissions on Pole Emploi Repository
  file:
    path: "{{ pole_emploi.path }}"
    state: directory
    owner: "{{ node.user }}" 
    group: "{{ node.user }}" 
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Create configuration file for server
  template:
    src: app-config.js.j2
    dest: "{{ pole_emploi.path }}/app/config.js"
    owner: "{{ node.user }}"
    group: "{{ node.user }}"
    mode: 0644

- name: Create configuration file for front-end
  template:
    src: pe-js-config.js.j2
    dest: "{{ pole_emploi.path }}/pe-js/config.js"
    owner: "{{ node.user }}"
    group: "{{ node.user }}"
    mode: 0644

- name: Create service file 
  template:
    src: poleemploi.service.j2
    dest: /etc/systemd/system/poleemploi.service
    owner: root
    group: root
    mode: 0644

- name: Start Pole Emploi Node Server and set it boot by default
  systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: poleemploi.service

- include: nginx_configuration.yml