---

- name: Create acme challenge vhost in sites-available
  template:
    src: ../templates/acme_challenge.j2
    dest: "/etc/nginx/sites-available/acme.conf"
    owner: root
    group: root
    mode: 0600
  vars:
    domain: "{{ pole_emploi_domain }}"
  notify: 'restart nginx'

- name: Ensure default vhost is absent
  file: 
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: 'restart nginx'

- name: Enable HTTP redirect for ACME Challenge
  file: 
    src: "/etc/nginx/sites-available/acme.conf"
    dest: "/etc/nginx/sites-enabled/acme.conf"
    state: link
  notify: 'restart nginx'

# This step is VERY important because it will triggers all triggered handlers to run. 
# We need to reload nginx before getting 
- meta: flush_handlers

- name: Create letsencrypt certificate
  shell: "certbot certonly --rsa-key-size 4096 --webroot -w /var/www/acme-challenges/ -m {{ letsencrypt_email }} --agree-tos -d {{ pole_emploi_domain }} --non-interactive"
  args:
    creates: "/etc/letsencrypt/live/{{ pole_emploi_domain }}"

- name: Create pole emploi vhost sites-available
  template:
    src: ../templates/pole-emploi.conf.j2
    dest: "/etc/nginx/sites-available/{{pole_emploi_domain}}.conf"
    owner: root
    group: root
    mode: 0600
  vars:
    domain: "{{ pole_emploi_domain }}"
  notify: 'restart nginx'

- name: Enable pole emploi site
  file: 
    src: "/etc/nginx/sites-available/{{pole_emploi_domain}}.conf"
    dest: "/etc/nginx/sites-enabled/{{pole_emploi_domain}}.conf"
    state: link
  notify: 'restart nginx'

- name: Disable acme challenge site
  file: 
    path: "/etc/nginx/sites-available/acme.conf"
    state: absent
  notify: 'restart nginx'

- name: Add certbot cronjob for cert renewal
  cron:
    name: pole_emploi_letsencrypt_renewal
    special_time: weekly
    job: "certbot renew --non-interactive --post-hook 'service nginx reload'"