---

- include_role:
    name: certbot_challenge
  vars:
    certbot_domain: "{{ pole_emploi_domain }}"

- name: Create pole emploi vhost sites-available
  template:
    src: ../templates/pole-emploi.conf.j2
    dest: "/etc/nginx/sites-available/{{pole_emploi_domain}}.conf"
    owner: root
    group: root
    mode: 0600
  vars:
    domain: "{{ pole_emploi_domain }}"
  notify: 'restart nginx'

- name: Enable pole emploi site
  file: 
    src: "/etc/nginx/sites-available/{{pole_emploi_domain}}.conf"
    dest: "/etc/nginx/sites-enabled/{{pole_emploi_domain}}.conf"
    state: link
  notify: 'restart nginx'

