---

- hosts: binome
  become: true
  roles:
    - docker
    - machine-learning
  post_tasks:
    - debug:
        msg: "Machine Learning is now configured and available at https://{{ machine_learning.domain }}/ !"
