---

- hosts: binome
  become: true
  roles:
    - nodejs
    - pole-emploi
  post_tasks:
    - debug:
        msg: "Pôle Emploi is now configured and available at https://{{ pole_emploi.domain }}/ and https://{{ pole_emploi.domain }}/notifications.html !"
