---
# The trailing slash indicates that we don't want to upload the folder but only its content
- name: Upload Monit configuration
  copy:
    src: ../resources/monit/
    dest: /etc/monit
  notify: restart monit

- name: Copy Monit main configuration
  template:
    src: ../templates/monitrc.j2
    dest: /etc/monit/monitrc
    owner: root
    group: root
    mode: 0600
  vars:
    - url: "{{ monit_smtp_url }}"
    - port: "{{ monit_smtp_port }}"
    - user_password: "{{ monit_smtp_password }}"
    - user: "{{ monit_smtp_user }}"
    - recipient: "{{ monit_smtp_recipient }}"
    - web_password: "{{ monit_httpd_password }}"
  notify: restart monit