---

- name: Create acme challenge vhost in sites-available
  template:
    src: ../templates/acme_challenge.j2
    dest: "/etc/nginx/sites-available/acme.conf"
    owner: root
    group: root
    mode: 0600
  vars:
    domain: "{{ monit_status_domain }}"
  notify: 'restart nginx'

- name: Ensure default vhost is absent
  file: 
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: 'restart nginx'

- name: Enable HTTP redirect for ACME Challenge
  file: 
    src: "/etc/nginx/sites-available/acme.conf"
    dest: "/etc/nginx/sites-enabled/acme.conf"
    state: link
  notify: 'restart nginx'
