---

docker_edition: "ce"
docker_channel: "stable"
docker_version: "latest"

docker_install_docker_compose: True
docker_compose_version: "1.22.0"

docker_users: []

docker_apt_key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
docker_apt_key_server: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
docker_apt_repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_channel }}"
docker_apt_cache_time: 86400