---
docker:
  edition: "ce"
  version: "latest"
  compose:
    install: True
    version: "1.22.0"
  users: []
  apt:
    key_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"
    key_server: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    repository: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    cache_time: 86400
