---

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present
    force_apt_get: True
  notify: enable fail2ban

- name: Copy Fail2Ban main configuration
  template:
    src: ../templates/fail2ban.conf
    dest: /etc/fail2ban/fail2ban.conf
    owner: root
    group: root
    mode: 0644
  notify: restart fail2ban

- name: Copy Fail2Ban Jail configuration
  template:
    src: ../templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  vars:
    receiver: "{{ fail2ban_receiver_mail }}"
    sender: "{{ fail2ban_sender_email }}"
  notify: restart fail2ban
