---
- name: Ensure iptables is installed
  apt:
    name: iptables
    state: present
    force_apt_get: True

- name: Accept Established connections - Input
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Accept Established connections - OUTPUT
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow outgoing traffic on Loopback
  iptables:
    out_interface: lo
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming traffic on Loopback
  iptables:
    in_interface: lo
    chain: INPUT
    jump: ACCEPT

- name: Allow incoming ICMP traffic 
  iptables:
    protocol: icmp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing ICMP traffic 
  iptables:
    protocol: icmp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming SSH traffic on port 22 TCP
  iptables:
    destination_port: 22
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing SSH traffic on port 22 TCP
  iptables: 
    destination_port: 22
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming DNS traffic on port 53 UDP
  iptables:
    destination_port: 53
    protocol: udp
    chain: INPUT
    jump: ACCEPT

- name: Allow incoming DNS traffic on port 53 TCP
  iptables:
    destination_port: 53
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing DNS traffic on port 53 TCP
  iptables:
    destination_port: 53
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow outgoing DNS traffic on port 53 UDP
  iptables:
    destination_port: 53
    protocol: udp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow outgoing NTP traffic on port 123 UDP
  iptables:
    destination_port: 123
    protocol: udp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow outgoing HTTP traffic on port 80 TCP
  iptables:
    destination_port: 80
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow outgoing HTTPS traffic on port 443 TCP
  iptables:
    destination_port: 443
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming HTTPS traffic on port 443 TCP
  iptables:
    destination_port: 443
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow incoming HTTP traffic on port 80 TCP
  iptables:
    destination_port: 80
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow incoming SMTP traffic on port 25 TCP
  iptables:
    destination_port: 25
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing SMTP traffic on port 25 TCP
  iptables:
    destination_port: 25
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming SMTPS traffic on port 587 TCP
  iptables:
    destination_port: 587
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing SMTPS traffic on port 587 TCP
  iptables:
    destination_port: 587
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow outgoing POP3 traffic on port 110 TCP
  iptables:
    destination_port: 110
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming POP3 traffic on port 110 TCP
  iptables:
    destination_port: 110
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing POP3S traffic on port 995 TCP
  iptables:
    destination_port: 995
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming POP3S traffic on port 995 TCP
  iptables:
    destination_port: 995
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing IMAP traffic on port 143 TCP
  iptables:
    destination_port: 143
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming IMAP traffic on port 143 TCP
  iptables:
    destination_port: 143
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing Github traffic on port 9418 TCP
  iptables:
    destination_port: 9418
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming Github traffic on port 9418 TCP
  iptables:
    destination_port: 9418
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Allow outgoing WHOIS traffic on port 43 TCP
  iptables:
    destination_port: 43
    protocol: tcp
    chain: OUTPUT
    jump: ACCEPT

- name: Allow incoming WHOIS traffic on port 43 TCP
  iptables:
    destination_port: 43
    protocol: tcp
    chain: INPUT
    jump: ACCEPT

- name: Set default Policy Rule to DROP on INPUT Chain
  iptables:
    chain: INPUT
    policy: DROP

- name: Set default Policy Rule to DROP on FORWARD Chain
  iptables:
    chain: FORWARD
    policy: DROP

- name: Set default Policy Rule to DROP on OUTPUT Chain
  iptables:
    chain: OUTPUT
    policy: DROP
