---

- name: Clone Machine Learning repository
  git:
    repo: 'https://github.com/EPSIBordeaux/machine-learning.git'
    dest: "{{machine_learning.path}}"

- name: Build required docker images
  make: 
    chdir: "{{ machine_learning.path }}"
    target: install

- name: Start Machine Learning Docker Container
  docker_service:
    state: present
    project_src: "{{ machine_learning.path }}"
    files: prod.yml

- include_role:
    name: certbot_challenge
  vars:
    certbot_domain: "{{ machine_learning.domain }}"

- name: Create machine learning vhost sites-available
  template:
    src: ../templates/machine-learning.conf.j2
    dest: "/etc/nginx/sites-available/{{ machine_learning.domain }}.conf"
    owner: root
    group: root
    mode: 0600
  vars:
    domain: "{{ machine_learning.domain }}"
  notify: 'restart nginx'

- name: Enable machine learning site
  file: 
    src: "/etc/nginx/sites-available/{{machine_learning.domain}}.conf"
    dest: "/etc/nginx/sites-enabled/{{machine_learning.domain}}.conf"
    state: link
  notify: 'restart nginx'

