---

- name: Ensure PHP required packages are installed.
  apt: 
    name: 
      - apt-transport-https 
      - lsb-release 
      - ca-certificates
    state: present

- name: Add PHP 7.2 repository apt key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- name: Add PHP 7.2 repositories.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://packages.sury.org/php/ {{ ansible_distribution_release }} main"
  register: php_repo

- name: Update APT cache if needed
  apt: 
    update_cache: yes
    force_apt_get: True
  when: php_repo.changed

- name: Ensure PHP 7.2 and some extensions are installed.
  apt:
    name: 
      - php7.2-fpm
      - php7.2-cli 
      - php7.2-common 
      - php7.2-curl 
      - php7.2-gd 
      - php7.2-json 
      - php7.2-mbstring 
      - php7.2-mysql 
      - php7.2-opcache 
      - php7.2-readline 
      - php7.2-xml
    state: present
    force_apt_get: True
  notify: restart php

- include: composer.yml