---

- name: Ensure NodeJS required packages are installed.
  apt: 
    name:
        - build-essential
        - libssl-dev
        - apt-transport-https
    state: present

- name: Add Nodesource APT key.
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add Node repositories.
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb https://deb.nodesource.com/node_{{ node.version }} {{ ansible_distribution_release }} main"
    - "deb-src https://deb.nodesource.com/node_{{ node.version }} {{ ansible_distribution_release }} main"
  register: node_repo

- name: Update APT cache if needed
  apt: 
    update_cache: yes
    force_apt_get: True
  when: node_repo.changed

- name: Ensure Node.js and npm are installed.
  apt:
    name: nodejs={{ node.version|regex_replace('x', '') }}* 
    state: present
    force_apt_get: True

- name: Create a NodeJS User
  user:
    name: "{{ node.user }}"
    state: present
    system: yes

- name: Create npm global directory
  file:
    path: "{{ node.npm_prefix }}"
    owner: "{{ node.user }}"
    group: "{{ node.user }}"
    state: directory

- name: Ensure Node-Gyp is installed globally
  npm:
    name: "node-gyp"
    version: "latest"
    global: yes
    state: latest
  environment:
    NPM_CONFIG_PREFIX: "{{ node.npm_prefix }}"
    NODE_PATH: "{{ node.npm_prefix }}/lib/node_modules"

- name: Add global npm package binary directory to global $PATH.
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644
