---

- name: Clone Custom Bin Repository
  git:
    repo: 'https://github.com/sylvainmetayer/bin.git'
    dest: "{{ custom_bin.path }}"

# Only simple word, without "." or whathever and exclude "LICENSE" file. 
# This way, we match all scripts
- name: Find all managed scripts
  find:
    paths: "{{ custom_bin.path }}"
    patterns: '^[^LICENSE|\.]\w+$'
    use_regex: yes
  register: custom_bin_files

- name: Ensure permissions of Custom Bin Repository
  file:
    dest: "{{ item.path }}"
    owner: root
    group: binome
    mode: 0775
  with_items: 
    - "{{ custom_bin_files.files }}"

- name: Update path with bin git repo
  lineinfile:
    dest: "/home/{{ item }}/.profile"
    state: present
    line: 'PATH=$PATH:{{ custom_bin.path }}'
  with_items: 
    - "{{ users }}"
