---
- name: Locales generation
  locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ locales }}" 

- name: Set default locale
  lineinfile:
    dest:   /etc/default/locale
    regexp: "LANG="
    line:   "LANG={{ default_locale }}"
