---
- name: Ensure group "binome" exists
  group:
    name: binome
    state: present

- name: Create users
  user:
    name: "{{ item }}"
    password: "{{ item | password_hash('sha512') }}"
    shell: /bin/bash
    update_password: on_create
    groups: ["sudo", "binome"]
  register: user_creation
  with_items:
    - "{{ users }}"

- name: Force users to change password on first connection
  shell: chage -d 0 {{ item }}
  when: user_creation.changed
  with_items:
    - "{{ users }}"

# We want to iterate over all defined SSH keys for each user
# See https://stackoverflow.com/a/50711744/6187576
- name: Add users SSH public keys to allow connection
  authorized_key:
    user: "{{ item.0.key }}"
    state: present
    key: '{{ item.1 }}'
  loop: "{{ ssh_keys | dict2items | subelements('value') }}"
