---

- name: restart nginx
  systemd:
    name: 'nginx'
    enabled: true
    state: 'restarted'
  listen: "restart nginx"

- name: restart monit
  systemd: 
    name: "monit"
    enabled: true
    state: "restarted"
  listen: "restart monit"
  
- name: restart ssh
  systemd:
    name: 'ssh'
    state: 'restarted'
  listen: "restart ssh"

- name: enable fail2ban
  systemd:
    state: started
    enabled: true
    name: fail2ban
  listen: "enable fail2ban"

- name: restart fail2ban
  systemd:
    state: restarted
    name: fail2ban
  listen: "restart fail2ban"

- name: restart php
  systemd:
    state: restarted
    name: php7.2-fpm
  listen: "restart php"
