---

- name: Clone Telegram Bot repository
  git:
    repo: 'https://github.com/EPSIBordeaux/Telegram_Bot.git'
    dest: "{{ telegram_bot.path }}"

- name: Install dependencies
  npm:
    path: "{{ telegram_bot.path }}"

- name: Set permissions on Telegram Bot Repository
  file:
    path: "{{ telegram_bot.path }}"
    state: directory
    owner: "{{ nodejs_user }}" 
    group: "{{ nodejs_user }}" 
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Create environnment file for the application
  template:
    src: .env.j2
    dest: "{{ telegram_bot.path }}/.env"
    owner: "{{ nodejs_user }}"
    group: "{{ nodejs_user }}"
    mode: 0644

- name: Create service file 
  template:
    src: telegram_bot.service.j2
    dest: /etc/systemd/system/telegram_bot.service
    owner: root
    group: root
    mode: 0644

- name: Start Telegram Bot Server and set it boot by default
  systemd:
    state: restarted
    enabled: true
    daemon_reload: yes
    name: telegram_bot.service

- include: nginx_configuration.yml