---

- name: Install NGINX
  apt:
    name: nginx
    state: present
    force_apt_get: True

- name: Creates SSL directory
  file:
    path: /etc/nginx/ssl
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Generate dhparams key
  shell: openssl dhparam -dsaparam -out /etc/nginx/ssl/dhparam.pem 4096
  args:
    creates: /etc/nginx/ssl/dhparam.pem

- name: Generate ticket session key
  shell: openssl rand -out /etc/nginx/ssl/ticket.key 48
  args:
    creates: /etc/nginx/ssl/ticket.key

# The fact that there is no trailing slash indicates that we want to upload the folder AND its content
- name: Upload NGINX "includes" directory
  copy:
    src: ../resources/includes
    dest: /etc/nginx

- name: Upload NGINX nginx configuration
  copy:
    src: ../resources/nginx.conf
    dest: /etc/nginx/nginx.conf

# TODO Server Token OFF to not know NGINX version