---

- name: Clone Expert System repository
  git:
    repo: 'https://github.com/EPSIBordeaux/epsi-expert-system.git'
    dest: "{{ expert_system.path }}"

- name: Set permissions on Expert System Repository
  file:
    path: "{{ expert_system.path }}"
    state: directory
    owner: "{{ node.user }}" 
    group: "{{ node.user }}" 
    mode: u=rwX,g=rX,o=rX
    recurse: yes

- name: Install dependencies
  npm:
    path: "{{ expert_system.path }}"

- name: Create service file 
  template:
    src: expertsystem.service.j2
    dest: /etc/systemd/system/expertsystem.service
    owner: root
    group: root
    mode: 0644

- name: Start Expert System Node Server and set it boot by default
  systemd:
    state: started
    enabled: true
    daemon_reload: yes
    name: expertsystem.service

- include: nginx_configuration.yml