---

- name: Add Docker GPG key
  apt_key:
    id: "{{ docker.apt.key_id }}"
    url: "{{ docker.apt.key_server }}"

- name: Configure Docker APT repository
  apt_repository:
    repo: "{{ docker.apt.repository }}"

- name: Install Docker
  apt:
    name: "docker-{{ docker.edition }}"
    update_cache: True
    cache_valid_time: "{{ docker.apt.cache_time }}"
    state: "latest"

- name: Install Python for managing Docker login credentials
  apt:
    name: "{{ item }}"
    update_cache: True
    cache_valid_time: "{{ docker.apt.cache_time }}"
  with_items:
    - "python-pip"
    - "python"

- name: Install Pip docker packages
  pip:
    name: "{{ item }}"
  with_items:
    - docker-compose
    - docker

# See https://github.com/ansible/ansible/issues/37200#issuecomment-381158216
- name: Install Pip Requests for PIP
  pip:
    name: requests
    version: 2.18.1

- name: Add user(s) to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: True
  loop: "{{ docker.users }}"
  when: docker_users

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker.compose.version }}/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"
  when: docker.compose.install
