---

- name: Add Docker GPG key
  apt_key:
    id: "{{ docker_apt_key_id }}"
    url: "{{ docker_apt_key_server }}"

- name: Configure Docker APT repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"

- name: Install Docker
  apt:
    name: "docker-{{ docker_edition }}"
    update_cache: True
    cache_valid_time: "{{ docker_apt_cache_time }}"
    state: "latest"

- name: Install Python for managing Docker login credentials
  apt:
    name: "{{ item }}"
    update_cache: True
    cache_valid_time: "{{ docker_apt_cache_time }}"
  with_items:
    - "python-pip"
    - "python"

- name: Install Pip docker packages
  pip:
    name: "{{ item }}"
  with_items:
    - docker-compose
    - docker-py
    # - docker
    # - setuptools

- name: Add user(s) to "docker" group
  user:
    name: "{{ item }}"
    groups: "docker"
    append: True
  loop: "{{ docker_users }}"
  when: docker_users

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "/usr/local/bin/docker-compose"
    force: True
    owner: "root"
    group: "root"
    mode: "0755"
  when: docker_install_docker_compose
