---

- import_playbook: setup.yml

- import_playbook: applications/expert-system.yml

- import_playbook: applications/machine-learning.yml

- import_playbook: applications/pole-emploi.yml

- import_playbook: applications/pong.yml

- import_playbook: applications/telegram_bot.yml

- import_playbook: applications/monit.yml