---

- name: Clone CodiMD Docker repository
  git:
    repo: 'https://github.com/hackmdio/codimd-container.git'
    dest: "{{ codimd.path }}"
    
- name: Start CodiMD Docker Container
  docker_service:
    state: present
    project_src: "{{ codimd.path }}"

- include: nginx_configuration.yml