---

- name: "Clone CodiMD Docker repository"
  git:
    repo: 'https://github.com/hackmdio/codimd-container.git'
    dest: /opt/codimd

- name: Start CodiMD Docker Containers
  docker_service:
    state: present
    project_src: /opt/codimd

# - name: "Create user {{ item }}"
#  command: "bin/manage_users --pass {{ item }} --add {{ item }}"
#  args: 
#      chdir: /opt/codimd
#  with_items: "{{ codimd_users }}"
#  when: codimd_assets.changed

- include: nginx_configuration.yml