---

- include_role:
    name: certbot_challenge
  vars:
    certbot_domain: "{{ codimd.domain }}"

- name: Create CodiMD vhost sites-available
  template:
    src: ../templates/codimd.conf.j2
    dest: "/etc/nginx/sites-available/{{ codimd.domain }}.conf"
    owner: root
    group: root
    mode: 0600
  notify: 'restart nginx'

- name: Enable CodiMD site
  file: 
    src: "/etc/nginx/sites-available/{{ codimd.domain }}.conf"
    dest: "/etc/nginx/sites-enabled/{{ codimd.domain }}.conf"
    state: link
  notify: 'restart nginx'

